- name: Download and UnZip the {{COMPONENT}} Content
  ansible.builtin.unarchive:
    src: https://github.com/siddhudeva/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
  when: GIT_DOWNLOAD is defined

- name: Download {{COMPONENT}} from Nexus
  ansible.builtin.get_url:
    url: http://nexus1.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}.{{APP_VERSION}}.zip
    dest: /tmp
    username: admin
    password: Admin123
  when: GIT_DOWNLOAD is not defined


# "{{NEXUS3_USERNAME}}"
# "{{NEXUS3_PASSWORD}}"